name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-east1
  SA_KEY_JSON: ${{ secrets.RUN_SA_KEY }}
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/google-github-actions/auth@v2
        with:
          version: "363.0.0"
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      # Build and push image to Google Container Registry
      - name: Build
        run: gcloud builds submit --tag gcr.io/$RUN_PROJECT/$RUN_PROJECT:$GITHUB_SHA

      - name: Deploy
        run: gcloud run deploy $RUN_SA_KEY --image gcr.io/$RUN_SA_KEY/$RUN_SA_KEY:$GITHUB_SHA --platform managed --region $GCP_REGION


