name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t saikartik240/node-gcp-app:$GITHUB_SHA .

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push saikartik240/node-gcp-app:$GITHUB_SHA
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name node_workflow-container saikartik240/node-gcp-app

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.RUN_SA_KEY }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy node-gcp-app \
          --image saikartik240/node-gcp-app:$GITHUB_SHA \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
