name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build the Docker Image
        run: docker build -t saikartik240/node_workflow .

      - name: Push to DockerHub
        run: docker push saikartik240/node_workflow

  deploy:
    needs: build
    runs-on: self-hosted
    
    steps:
      - name: Pull Docker Image
        run: |
          echo "Pulling Docker image: saikartik240/node_workflow"
          docker pull saikartik240/node_workflow:latest

      - name: Check Docker Images
        run: sudo docker images

      - name: Delete old Docker container 
        run: sudo docker rm -f node_workflow-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 8000:8000 --name node_workflow-container saikartik240/node_workflow
