name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker Image
        run: docker build -t saikartik240/node_workflow .

      - name: Push to DockerHub
        run: docker push saikartik240/node_workflow
  deploy:
      needs: build
      runs-on: self-hosted
  
      steps:
        - name: Pull Docker Image
          run: sudo docker pull saikartik240/node_workflow:latest
  
        - name: Delete old Docker container 
          run: sudo docker rm -f nodeApp-container || true 
  
        - name: Run Docker Container
          run: sudo docker run -d -p 3000:8000 --name nodeApp-container saikartik240/node_workflow
